### ISSUE TITLE
Change the submit value in the property field?

### ISSUE THREAD

**Issue by hendrisoni** [pr0gramista/super_form#17]
hi, can i change the submit value in the property field?. 
example:;
```
onSubmitValue:(value){
return value.removeChar(',');
}
```

in superFormField im adding Money inputFormatters, and the value has Char "," in '99,999.00'. can i change this to '99999.99'. thanks and I'm new to flutter. This SuperForm is a great library for me.

**Comment by pr0gramista** [comment]
Hi, thanks for reaching out!

Currently there is no concept of value transformers for fields. This might change as I am currently working on date fields, but there are some issues with overall idea like multiple inputs for same field.

What I would recommend for now is to transform the value in onSubmit callback. Let's say you want to have double as a end result:
```
onSubmit: (values) {
  final money = double.tryParse(values["money"].replaceAll(',', ''));

  print(money)
}
```
In a sense providing SuperForm's initialValues and onSubmit works as toForm and fromForm, similar to toJson and fromJson.

If this doesn't suit your needs you can also implement your own custom field. You can start by copying the code of TextSuperFormField and change logic in onTextChange or apply very custom TextController instance.
https://raw.githubusercontent.com/pr0gramista/super_form/master/lib/src/fields/text_super_form_field.dart

Let me know if this solves your problem!

**Comment by hendrisoni** [comment]
thanks for the answer, really appreciate.

yes i think to manipulate that function. including initialValues which I need is in fields. but this requires extending the class.

Thank you.
